# Generated by Django 4.2.6 on 2023-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("product", "제품, 서비스 소개"), ("event", "이벤트, 소식 전하기")],
                        max_length=10,
                    ),
                ),
                ("contents", models.TextField()),
                ("output", models.TextField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
